import scrapy


class JobItem(scrapy.Item):
    source = scrapy.Field()
    source_job_id = scrapy.Field()
    title = scrapy.Field()
    company = scrapy.Field()
    company_slug = scrapy.Field()
    department = scrapy.Field()
    seniority = scrapy.Field()
    seniority_confidence = scrapy.Field()
    years_experience_min = scrapy.Field()
    years_experience_max = scrapy.Field()
    location = scrapy.Field()
    location_city = scrapy.Field()
    location_state = scrapy.Field()
    location_country = scrapy.Field()
    is_remote_friendly = scrapy.Field()
    remote_type = scrapy.Field()
    employment_type = scrapy.Field()
    salary_min = scrapy.Field()
    salary_max = scrapy.Field()
    salary_currency = scrapy.Field()
    description_html = scrapy.Field()
    description_text = scrapy.Field()
    tags = scrapy.Field()
    skills = scrapy.Field()
    platform_keywords = scrapy.Field()
    primary_cloud_platforms = scrapy.Field()
    is_multi_cloud = scrapy.Field()
    is_platform_heavy = scrapy.Field()
    apply_url = scrapy.Field()
    posted_at = scrapy.Field()
    quality_score = scrapy.Field()
    quality_flags = scrapy.Field()
    description_word_count = scrapy.Field()
